export const GET_USER_COUNT_INIT = "GET_USER_COUNT_INIT";
export const GET_USER_COUNT_SUCCESS = "GET_USER_COUNT_SUCCESS";
export const GET_USER_COUNT_ERROR = "GET_USER_COUNT_ERROR";

export const GET_DOCTOR_COUNT_INIT = "GET_DOCTOR_COUNT_INIT";
export const GET_DOCTOR_COUNT_SUCCESS = "GET_DOCTOR_COUNT_SUCCESS";
export const GET_DOCTOR_COUNT_ERROR = "GET_DOCTOR_COUNT_ERROR";
//plopImport