//snippet rxconst
export const LAWYER_CATEGORY_FETCH_INIT = "LAWYER_CATEGORY_FETCH_INIT";
export const LAWYER_CATEGORY_FETCH_SUCCESS = "LAWYER_CATEGORY_FETCH_SUCCESS";
export const LAWYER_CATEGORY_FETCH_FAIL = "LAWYER_CATEGORY_FETCH_FAIL";
//plopImport
